[build]
  publish = "dist/"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  force = true
  from = "/confirmation.html"
  status = 200
  to = "/.netlify/functions/api/:splat"
